travis:
  secure:
    BINSTAR_TOKEN: DjRyOi/G2U4WwbSvQ4+k2vTCjXMtVeMAHHmvVQgNN5IMzCo7pYw9CTmTFqLzNdiduNmZALqRzB8h7F9DwzGUdXpkNpqOgl03GM4pMNhFbrw/EFzTX9hsSGiUXac5gtPx8V/QV2Uo1aQHgBSUkz9B4csV/17ro08Xiv+dBfh41Lk1WIWVvBMKOgrifGUsKoUBsVhW5AKWOMG8KBuvD2qKBOvSsWOp35n1YNqXzaICMh1tl8w7B+GrnJHLhHKd09sz4GY4aX5jZMZbMvCvwDMCoVZfDPWg3vEj6Wxq/+MOAWS/4avooFIbXPGcJMVezh9f+dlZAsewA/HENroAY2n/twpjNGjrksxkuY3DTDMI1K6QILqlgVJvkAZWsmkUvRYTWIU+lJTZFERfwb9CuCkmhUm5Jd1Cbr3CATxfB8wJXV+Sd+LqN9yIC0sl0xu4M+pj4FRGsiTybkJ/3aGEE7M9jN4mY9dKtuK7vFFptBySaqMPtEJ/INekgxHNqiBbTQ/iubXeCHuySvIt/Lz0a0fHsS2DwcY3qhyg/9WPbptCcqYWkBXzJmeV/qnw/xv9IiqVz8v/6cDMSecrPiLWwIXA97pW5sWY6b7qgWGmTChRA7wW4YuwQsPAjA80tAM0qdApoZlpG32KwaMRTsfq1BxC5Ch/+ODf9d2osqu9ObhMiPQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
