travis:
  secure:
    BINSTAR_TOKEN: b0szEOltvPI51PIDfM4PdjnARcoQlO/xxSj6BTXckGoqC/pmoBWmID8+vxH4e7mUvaD14AXB5HaOX8Fqw2BbXfGLLWczvI1IVGF5FUp+mKyFY5QZ26wD1w1Q1wsUQ7QARMTJoqR6BFWzqyYerFeE9Vy2xKeaGeSEEHeWilEREsYfztToKo8dDRBTwfmwrb2fwQNP8EwXnso3M1Ya2vd/3c+g+raEF8MiIMKqBNqrZ07/3PBy18OhKCA1ZggieAwhr7TvCaOaX3N87CJfphvMNkdD0EW87TpIWZQsqy08nWvD7GpdHPWg7MQ+92UJ+bJUDIFenk3pNkGJYBKm8oD+anUg2DKqnzDLc/kRWdu2/3ZTXKrvPO4PvDHiTq1KmcyJmo73kxxDek6j9ZzQuNm2Nt2hjlDdr7lRv5/MAPJ6YO0wom4HpFcu8eqK/8gGXwZix3Lb5EZj60Ej7ZZVEvqVuSXKGMfvIjUAf0PhCM53T6r0lMbMQ0a3QxFGA0KXAO0rO+UYvSNpPcx+ydr0E4nKiujXZYhZiZR/7Urijo3DRQCAsYydKqpgtsHETtbwu6+DxYWZO/VAYR9vFtT8SZYexgs7xmVsnSb5E5G5EtBaM78UVVijgm6RdlGyWlEE7LvrjoPRd9SSQsqDXzPhJef+GfY5t96cWdS6yaIRCQIE5kk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
