travis:
  secure:
    BINSTAR_TOKEN: dTWOaX8ljsq126b2Gb4L6n306fJOj45XapWkGABV4pc6Bbuxw2eIg0hUD6nSfgpXxsaXmrkhPSxdazJrEVAaRnLFv039okgbZ1wWxeH5AdVFqaMWXmeF3aEITIpnHpLrvZ7TXvC7wh+64Vyyf1IbJwpU7Goz45BoeWYq+WRGU9/K5QSyv6x0AHTVtTRaCBpdz8XOfAk9nIa2esqN/pXN97cXWpjzaj35TpNdxYpAWLxuJ8RArrH6LFaU2X+12HY4OaURScfexAwW+E5M0eYdslmXh5yuTxvbjOHfTE4UlEB9dM/KHpMRkthxDCevoSsVWVUTEynJSPh5AGdlx+bOnMjmK2fmD2w7Jn4/BboUMaqpCUyKF/q5zRgTQbtSB+0+5ekmnwb5LanTMQD8OJIqeEmz7YCN7lIj0mKKaca2NFawfVmhcCUzWq2DSxpzeOn9hyzBmPLozWTzw8pFrohb54AIGfkh+WUAoJ6nET7/qpzCQq8hwMYE9QaHjqoPnRpu1UZRh06g6FcdpAUJhGT8eCFdxjEp57W98ZmvqHyiDLbnZK5aJy/h5kXFPVbdzIHAEiJkvjxf85plxJxqotTYRnzK0QX/hablRDJVY9N5lDuQEruvVJtYLcJyLwuBs/273FJjQUPK9Hb3V4rnqGjKW5lL7msKCsWiVLV/3O2yW7E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
